<a href="https://colab.research.google.com/github/ben854719/Patient-Electronic-Health-Record-System/blob/main/Pandas_New_Drugs_Patient_Record.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [4]:
# Import the dataset for the risk management of the new drugs by Health Canada.
risk_management_new_drug_health_canada = pd.read_csv("risk management_new drug_health canada.csv")
display(risk_management_new_drug_health_canada.head(61))

,Lead_Office_Fro,Product_Line,DSTS_No,SAP_No,Product_Name,Active_Ingred,Review_Type,Date_Received,Date_Assigned,Date_Finish,Gender,Age,Provinces,Fiscal_Year
0,MBBNHPB,Biologic,212387,3010678,BIOTHRAX,ANTHRAX VACCINE ADSORBED,RMP NDS,16-Feb-18,08-May-18,16-Sep-18,Male,23,Ontario,2018
1,MBBNHPB,Biologic,211541,3010633,KAMRAB,ANTI-RABIES IMMUNOGLOBIN (HUMAN),RMP NDS,12-Jan-18,27-Feb-18,04-Jun-18,Male,22,Ontario,2018
2,MBBNHPB,Biologic,210935,3010673,JIVI,"ANTIHEMOPHILIC FACTOR (RECOMBINANT), PEGYLATED",RMP NDS,08-Jan-18,13-Mar-18,05-Jul-18,Male,33,Ontario,2018
3,MBBNHPB,Biologic,208364,3010585,DWP-40,BOTULINUM TOXIN TYPE A,RMP NDS,20-Oct-17,30-Jan-18,29-May-18,Male,44,Ontario,2018
4,MBBNHPB,Biologic,212066,3010657,UNITUXIN,DINUTUXIMAB,RMP NDS,01-Feb-18,09-May-18,16-Sep-18,Male,55,Ontario,2018
5,MBBNHPB,Biologic,214080,3010766,NIVESTYM (BIOSIMILAR TO NEUPOGEN),FILGRASTIM,RMP NDS,16-Apr-18,13-Jun-18,16-Oct-18,Male,55,Ontario,2018
6,MBBNHPB,Biologic,212016,3010677,ZARXIO (BIOSIMILAR TO NEUPOGEN),FILGRASTIM,RMP NDS,05-Feb-18,08-May-18,17-Sep-18,Male,55,Ontario,2018
7,MBBNHPB,Biologic,214058,3010742,RIXATHON,RITUXIMAB,RMP NDS,20-Apr-18,19-Jul-18,19-Nov-18,Male,65,Ontario,2018
8,MBBNHPB,Biologic,566,3010655,TRAZIMERA,TRASTUZUMAB,RMP NDS,01-Feb-18,01-May-18,07-Sep-18,Female,65,Quebec,2018
9,MBBNHPB,Biologic,213188,3010711,VONVENDI,VON WILLEBRAND FACTOR [RECOMBINANT],RMP NDS,19-Mar-18,04-Jul-18,07-Nov-18,Female,65,Quebec,2018
10,MBBNHPB,Biologic,218389,3010866,YESCARTA,AXICABTAGENE CILOLEUCEL,RMP NDS NAS,17-Aug-18,10-Sep-18,11-Dec-18,Female,65,Quebec,2018
11,MBBNHPB,Biologic,216239,3010798,CRYSVITA,BUROSUMAB,RMP NDS NAS,08-Jun-18,14-Jun-18,01-Oct-18,Female,66,Quebec,2018
12,MBBNHPB,Biologic,218718,3010869,LIBTAYO,CEMIPLIMAB,RMP NDS NAS,24-Aug-18,30-Aug-18,17-Dec-18,Female,66,Quebec,2018
13,MBBNHPB,Biologic,218145,3010864,OXERVATE,CENEGERMIN,RMP NDS NAS,14-Aug-18,17-Aug-18,24-Dec-18,Female,66,Quebec,2018
14,MBBNHPB,Biologic,216539,3010817,BRINEURA,CERLIPONASE ALFA,RMP NDS NAS,25-Jun-18,04-Jul-18,12-Oct-18,Female,66,Manitoba,2018
15,MBBNHPB,Biologic,212635,3010672,HEMILIBRA,EMICIZUMAB,RMP NDS NAS,05-Feb-18,19-Feb-18,12-Jun-18,Female,45,Manitoba,2018
16,MBBNHPB,Biologic,208607,3010533,AIMOVIG,ERENUMAB,RMP NDS NAS,06-Oct-17,15-Jan-18,11-May-18,Female,23,Manitoba,2018
17,MBBNHPB,Biologic,212276,3010636,PANHEMATIN,HEMIN FOR INJECTION,RMP NDS NAS,16-Jan-18,24-Jan-18,24-Apr-18,Female,60,Manitoba,2018
18,MBBNHPB,Biologic,213920,3010731,TAKHZYRO,LANADELUMAB INJECTION,RMP NDS NAS,27-Mar-18,10-Apr-18,27-Jul-18,Male,60,Manitoba,2018
19,MBBNHPB,Biologic,217184,3010835,LUTATHERA,LUTETIUM (177LU OXODOTREOTIDE,RMP NDS NAS,13-Jul-18,19-Jul-18,06-Nov-18,Male,60,Nova-Scotia,2018
20,MBBNHPB,Biologic,215753,3010815,SKYRIZI,RISANKIZUMAB,RMP NDS NAS,22-Jun-18,02-Oct-18,12-Feb-19,Male,60,Prince Edward Island,2018
21,MBBNHPB,Biologic,197713,3010900,EVENITY,ROMOSOZUMAB,RMP NDS NAS,22-Aug-18,11-Oct-18,22-Jan-19,Male,60,Alberta,2018
22,MBBNHPB,Biologic,213,3010705,KYMRIAH,TISAGENLECLEUCEL,RMP NDS NAS,09-Mar-18,15-Mar-18,03-Jul-18,Female,67,Alberta,2018
23,MPMDB,Pharmaceuticals,209478,209478,AVIR-ACETAMINOPHEN INJECTION,ACETAMINOPHEN,RMP NDS,15-Apr-18,31-Jul-18,10-Oct-18,Female,67,Alberta,2018
24,MPMDB,Pharmaceuticals,215660,3010782,SUBLOCADE,BUPRENORPHINE,RMP NDS,25-May-18,07-Jun-18,18-Oct-18,Female,67,Saskatchewan,2018
25,MPMDB,Pharmaceuticals,211635,3010664,CYSTADROPS,CYSTEAMINE HYDROCHLORIDE,RMP NDS,19-Dec-17,14-Feb-18,19-Jun-18,Female,67,Saskatchewan,2018
26,MPMDB,Pharmaceuticals,201005,3010702,SEGLUROMET,"ERTUGLIFLOZIN, METFORMIN",RMP NDS,03-Aug-18,19-Apr-18,07-Aug-18,Female,67,Manitoba,2018
27,MPMDB,Pharmaceuticals,211970,3010761,NYXOID,NALOXONE HYDROCHLORIDE DIHYDRATE,RMP NDS,29-Jan-18,14-May-18,12-Sep-18,Male,59,Manitoba,2018
28,MPMDB,Pharmaceuticals,212391,3010685,NETILDEX,"NETILMICIN, DEXAMETHASONE SODIUM PHOSPHATE",RMP NDS,20-Feb-18,30-Apr-18,31-Aug-18,Male,49,Manitoba,2018
29,MPMDB,Pharmaceuticals,208730,3010611,XERMELO,TELOTRISTAT ETIPRATE,RMP NDS,13-Dec-17,30-Apr-18,24-Aug-18,Male,38,New-Brunswick,2018
30,MPMDB,Pharmaceuticals,215268,215268,VERZENIO,ABEMACICLIB,RMP NDS NAS,14-Jun-18,09-Oct-18,14-Feb-19,Male,25,New-Brunswick,2018
31,MPMDB,Pharmaceuticals,214504,214504,CALQUENCE,ACALABRUTINIB,RMP NDS NAS,24-Apr-18,17-Jul-18,07-Nov-18,Male,26,New-Brunswick,2018
32,MPMDB,Pharmaceuticals,217349,217349,TRANSLARNA,ATALUREN,RMP NDS NAS,13-Sep-18,04-Oct-18,21-Feb-19,Male,29,New-Brunswick,2018
33,MPMDB,Pharmaceuticals,193687,3010732,OLUMIANT,BARICITINIB,RMP NDS NAS,27-Mar-18,13-Apr-18,16-Aug-18,Female,32,New-Brunswick,2018
34,MPMDB,Pharmaceuticals,208886,3010627,BELEODAQ,BELINOSTAT,RMP NDS NAS,04-Mar-18,05-Jun-18,10-Oct-18,Female,32,New-Brunswick,2018
35,MPMDB,Pharmaceuticals,210369,3010624,ALUNBRIG,BRIGATINIB,RMP NDS NAS,21-Dec-17,10-Jan-18,11-May-18,Female,34,New-Brunswick,2018
36,MPMDB,Pharmaceuticals,212831,212831,CABOMETYX,CABOZANTINIB,RMP NDS NAS,18-Apr-18,04-Jul-18,01-Nov-18,Female,34,Manitoba,2018
37,MPMDB,Pharmaceuticals,214572,3010762,VIZIMPRO,DACOMITINIB,RMP NDS NAS,03-May-18,26-Sep-18,30-Jan-19,Female,34,Manitoba,2018
38,MPMDB,Pharmaceuticals,212390,3010735,XYDALBA,DALBAVANCIN,RMP NDS NAS,10-Apr-18,30-Apr-18,07-Sep-18,Female,19,Manitoba,2018
39,MPMDB,Pharmaceuticals,207372,3010736,DEMYLOCAN,DECITABINE,RMP NDS NAS,27-Mar-18,25-Jul-18,07-Dec-18,Female,19,Manitoba,2018
40,MPMDB,Pharmaceuticals,211293,3010610,TRADEMARK (DORAVIRINE),DORAVIRINE,RMP NDS NAS,10-Jan-18,27-Feb-18,20-Jun-18,Female,19,Manitoba,2018
41,MPMDB,Pharmaceuticals,214391,3010750,RADICAVA,EDARAVONE,RMP NDS NAS,06-Apr-18,22-May-18,27-Sep-18,Female,24,Manitoba,2018
42,MPMDB,Pharmaceuticals,209513,3010614,ORILISSA,ELAGOLIX,RMP NDS NAS,12-Dec-17,26-Feb-18,29-Jun-18,Female,24,Newfloudland Labrador,2018
43,MPMDB,Pharmaceuticals,217033,217033,IDHIFA,ENASIDENIB MESYLATE,RMP NDS NAS,13-Jul-18,27-Aug-18,18-Dec-18,Female,24,Newfloudland Labrador,2018
44,MPMDB,Pharmaceuticals,193890,3010492,MONOFER,FERRIC DERISOMALTOSE,RMP NDS NAS,07-Sep-17,22-Jan-18,18-May-18,Female,25,Newfloudland Labrador,2018
45,MPMDB,Pharmaceuticals,214274,3010740,TEGSEDI,INOTERSEN SODIUM,RMP NDS NAS,11-Apr-18,23-Apr-18,26-Sep-18,Female,25,Newfloudland Labrador,2018
46,MPMDB,Pharmaceuticals,207006,3010462,SOLIQUA,"INSULINE GLARGINE, LIXISENATIDE",RMP NDS NAS,25-Jul-17,15-Nov-17,05-Jun-18,Female,25,Newfloudland Labrador,2018
47,MPMDB,Pharmaceuticals,208919,3010728,CRESEMBA,ISAVUCONAZOLE,RMP NDS NAS,01-Apr-18,28-Jun-18,25-Oct-18,Female,25,Newfloudland Labrador,2018
48,MPMDB,Pharmaceuticals,211732,3010712,VYZULTA,LATANOPROSTENE BUNOD,RMP NDS NAS,19-Mar-18,21-Mar-18,25-Jul-18,Female,44,Newfloudland Labrador,2018
49,MPMDB,Pharmaceuticals,215733,215733,LORBRENA,LORLATINIB,RMP NDS NAS,12-Jun-18,04-Sep-18,19-Dec-18,Female,44,Quebec,2018
50,MPMDB,Pharmaceuticals,216257,216257,VLEXIO,NICARDIPINE HYDROCHLORIDE,RMP NDS NAS,26-Oct-18,30-Jan-19,22-Mar-19,Male,44,Quebec,2018
51,MPMDB,Pharmaceuticals,210368,210368,VELTASSA,PATIROMER SORBITEX CALCIUM,RMP NDS NAS,04-Dec-17,10-Jul-18,07-Nov-18,Male,44,Quebec,2018
52,MPMDB,Pharmaceuticals,207545,3010577,FOLOTYN,PRALATREXATE,RMP NDS NAS,28-Jan-18,06-Mar-18,07-Jun-18,Male,55,Ontario,2018
53,MPMDB,Pharmaceuticals,207115,3010772,ONSTRYV (XADAGO),SAFINAMIDE,RMP NDS NAS,16-Mar-18,15-May-18,21-Sep-18,Male,55,Ontario,2018
54,MPMDB,Pharmaceuticals,196367,3010777,BELSOMRA,SUVOREXANT,RMP NDS NAS,15-May-18,13-Aug-18,19-Dec-18,Female,55,Ontario,2018
55,MPMDB,Pharmaceuticals,211292,3010625,SYMDEKO,"TEZACAFTOR, IVACAFTOR",RMP NDS NAS,28-Nov-17,29-Jan-18,18-May-18,Female,55,Ontario,2018
56,MPMDB,Pharmaceuticals,206099,3010617,TIBELLA,TIBOLONE,RMP NDS NAS,24-Aug-17,03-Jan-18,04-May-18,Female,60,Ontario,2018
57,MPMDB,Pharmaceuticals,209280,3010518,WAYLIVRA,VOLANESORSEN,RMP NDS NAS,20-Sep-17,16-Nov-17,18-Apr-18,Female,61,Quebec,2018
58,MPMDB,Pharmaceuticals,209280,209280,WAYLIVRA,VOLANESORSEN,RMP NDS NAS,21-Aug-18,04-Sep-18,07-Nov-18,Female,34,Quebec,2018

In [5]:
# Remove any duplication from the dataset.
risk_management_new_drug_health_canada = risk_management_new_drug_health_canada.drop_duplicates()
display(risk_management_new_drug_health_canada.head(59))

,Lead_Office_Fro,Product_Line,DSTS_No,SAP_No,Product_Name,Active_Ingred,Review_Type,Date_Received,Date_Assigned,Date_Finish,Gender,Age,Provinces,Fiscal_Year
0,MBBNHPB,Biologic,212387,3010678,BIOTHRAX,ANTHRAX VACCINE ADSORBED,RMP NDS,16-Feb-18,08-May-18,16-Sep-18,Male,23,Ontario,2018
1,MBBNHPB,Biologic,211541,3010633,KAMRAB,ANTI-RABIES IMMUNOGLOBIN (HUMAN),RMP NDS,12-Jan-18,27-Feb-18,04-Jun-18,Male,22,Ontario,2018
2,MBBNHPB,Biologic,210935,3010673,JIVI,"ANTIHEMOPHILIC FACTOR (RECOMBINANT), PEGYLATED",RMP NDS,08-Jan-18,13-Mar-18,05-Jul-18,Male,33,Ontario,2018
3,MBBNHPB,Biologic,208364,3010585,DWP-40,BOTULINUM TOXIN TYPE A,RMP NDS,20-Oct-17,30-Jan-18,29-May-18,Male,44,Ontario,2018
4,MBBNHPB,Biologic,212066,3010657,UNITUXIN,DINUTUXIMAB,RMP NDS,01-Feb-18,09-May-18,16-Sep-18,Male,55,Ontario,2018
5,MBBNHPB,Biologic,214080,3010766,NIVESTYM (BIOSIMILAR TO NEUPOGEN),FILGRASTIM,RMP NDS,16-Apr-18,13-Jun-18,16-Oct-18,Male,55,Ontario,2018
6,MBBNHPB,Biologic,212016,3010677,ZARXIO (BIOSIMILAR TO NEUPOGEN),FILGRASTIM,RMP NDS,05-Feb-18,08-May-18,17-Sep-18,Male,55,Ontario,2018
7,MBBNHPB,Biologic,214058,3010742,RIXATHON,RITUXIMAB,RMP NDS,20-Apr-18,19-Jul-18,19-Nov-18,Male,65,Ontario,2018
8,MBBNHPB,Biologic,566,3010655,TRAZIMERA,TRASTUZUMAB,RMP NDS,01-Feb-18,01-May-18,07-Sep-18,Female,65,Quebec,2018
9,MBBNHPB,Biologic,213188,3010711,VONVENDI,VON WILLEBRAND FACTOR [RECOMBINANT],RMP NDS,19-Mar-18,04-Jul-18,07-Nov-18,Female,65,Quebec,2018
10,MBBNHPB,Biologic,218389,3010866,YESCARTA,AXICABTAGENE CILOLEUCEL,RMP NDS NAS,17-Aug-18,10-Sep-18,11-Dec-18,Female,65,Quebec,2018
11,MBBNHPB,Biologic,216239,3010798,CRYSVITA,BUROSUMAB,RMP NDS NAS,08-Jun-18,14-Jun-18,01-Oct-18,Female,66,Quebec,2018
12,MBBNHPB,Biologic,218718,3010869,LIBTAYO,CEMIPLIMAB,RMP NDS NAS,24-Aug-18,30-Aug-18,17-Dec-18,Female,66,Quebec,2018
13,MBBNHPB,Biologic,218145,3010864,OXERVATE,CENEGERMIN,RMP NDS NAS,14-Aug-18,17-Aug-18,24-Dec-18,Female,66,Quebec,2018
14,MBBNHPB,Biologic,216539,3010817,BRINEURA,CERLIPONASE ALFA,RMP NDS NAS,25-Jun-18,04-Jul-18,12-Oct-18,Female,66,Manitoba,2018
15,MBBNHPB,Biologic,212635,3010672,HEMILIBRA,EMICIZUMAB,RMP NDS NAS,05-Feb-18,19-Feb-18,12-Jun-18,Female,45,Manitoba,2018
16,MBBNHPB,Biologic,208607,3010533,AIMOVIG,ERENUMAB,RMP NDS NAS,06-Oct-17,15-Jan-18,11-May-18,Female,23,Manitoba,2018
17,MBBNHPB,Biologic,212276,3010636,PANHEMATIN,HEMIN FOR INJECTION,RMP NDS NAS,16-Jan-18,24-Jan-18,24-Apr-18,Female,60,Manitoba,2018
18,MBBNHPB,Biologic,213920,3010731,TAKHZYRO,LANADELUMAB INJECTION,RMP NDS NAS,27-Mar-18,10-Apr-18,27-Jul-18,Male,60,Manitoba,2018
19,MBBNHPB,Biologic,217184,3010835,LUTATHERA,LUTETIUM (177LU OXODOTREOTIDE,RMP NDS NAS,13-Jul-18,19-Jul-18,06-Nov-18,Male,60,Nova-Scotia,2018
20,MBBNHPB,Biologic,215753,3010815,SKYRIZI,RISANKIZUMAB,RMP NDS NAS,22-Jun-18,02-Oct-18,12-Feb-19,Male,60,Prince Edward Island,2018
21,MBBNHPB,Biologic,197713,3010900,EVENITY,ROMOSOZUMAB,RMP NDS NAS,22-Aug-18,11-Oct-18,22-Jan-19,Male,60,Alberta,2018
22,MBBNHPB,Biologic,213,3010705,KYMRIAH,TISAGENLECLEUCEL,RMP NDS NAS,09-Mar-18,15-Mar-18,03-Jul-18,Female,67,Alberta,2018
23,MPMDB,Pharmaceuticals,209478,209478,AVIR-ACETAMINOPHEN INJECTION,ACETAMINOPHEN,RMP NDS,15-Apr-18,31-Jul-18,10-Oct-18,Female,67,Alberta,2018
24,MPMDB,Pharmaceuticals,215660,3010782,SUBLOCADE,BUPRENORPHINE,RMP NDS,25-May-18,07-Jun-18,18-Oct-18,Female,67,Saskatchewan,2018
25,MPMDB,Pharmaceuticals,211635,3010664,CYSTADROPS,CYSTEAMINE HYDROCHLORIDE,RMP NDS,19-Dec-17,14-Feb-18,19-Jun-18,Female,67,Saskatchewan,2018
26,MPMDB,Pharmaceuticals,201005,3010702,SEGLUROMET,"ERTUGLIFLOZIN, METFORMIN",RMP NDS,03-Aug-18,19-Apr-18,07-Aug-18,Female,67,Manitoba,2018
27,MPMDB,Pharmaceuticals,211970,3010761,NYXOID,NALOXONE HYDROCHLORIDE DIHYDRATE,RMP NDS,29-Jan-18,14-May-18,12-Sep-18,Male,59,Manitoba,2018
28,MPMDB,Pharmaceuticals,212391,3010685,NETILDEX,"NETILMICIN, DEXAMETHASONE SODIUM PHOSPHATE",RMP NDS,20-Feb-18,30-Apr-18,31-Aug-18,Male,49,Manitoba,2018
29,MPMDB,Pharmaceuticals,208730,3010611,XERMELO,TELOTRISTAT ETIPRATE,RMP NDS,13-Dec-17,30-Apr-18,24-Aug-18,Male,38,New-Brunswick,2018
30,MPMDB,Pharmaceuticals,215268,215268,VERZENIO,ABEMACICLIB,RMP NDS NAS,14-Jun-18,09-Oct-18,14-Feb-19,Male,25,New-Brunswick,2018
31,MPMDB,Pharmaceuticals,214504,214504,CALQUENCE,ACALABRUTINIB,RMP NDS NAS,24-Apr-18,17-Jul-18,07-Nov-18,Male,26,New-Brunswick,2018
32,MPMDB,Pharmaceuticals,217349,217349,TRANSLARNA,ATALUREN,RMP NDS NAS,13-Sep-18,04-Oct-18,21-Feb-19,Male,29,New-Brunswick,2018
33,MPMDB,Pharmaceuticals,193687,3010732,OLUMIANT,BARICITINIB,RMP NDS NAS,27-Mar-18,13-Apr-18,16-Aug-18,Female,32,New-Brunswick,2018
34,MPMDB,Pharmaceuticals,208886,3010627,BELEODAQ,BELINOSTAT,RMP NDS NAS,04-Mar-18,05-Jun-18,10-Oct-18,Female,32,New-Brunswick,2018
35,MPMDB,Pharmaceuticals,210369,3010624,ALUNBRIG,BRIGATINIB,RMP NDS NAS,21-Dec-17,10-Jan-18,11-May-18,Female,34,New-Brunswick,2018
36,MPMDB,Pharmaceuticals,212831,212831,CABOMETYX,CABOZANTINIB,RMP NDS NAS,18-Apr-18,04-Jul-18,01-Nov-18,Female,34,Manitoba,2018
37,MPMDB,Pharmaceuticals,214572,3010762,VIZIMPRO,DACOMITINIB,RMP NDS NAS,03-May-18,26-Sep-18,30-Jan-19,Female,34,Manitoba,2018
38,MPMDB,Pharmaceuticals,212390,3010735,XYDALBA,DALBAVANCIN,RMP NDS NAS,10-Apr-18,30-Apr-18,07-Sep-18,Female,19,Manitoba,2018
39,MPMDB,Pharmaceuticals,207372,3010736,DEMYLOCAN,DECITABINE,RMP NDS NAS,27-Mar-18,25-Jul-18,07-Dec-18,Female,19,Manitoba,2018
40,MPMDB,Pharmaceuticals,211293,3010610,TRADEMARK (DORAVIRINE),DORAVIRINE,RMP NDS NAS,10-Jan-18,27-Feb-18,20-Jun-18,Female,19,Manitoba,2018
41,MPMDB,Pharmaceuticals,214391,3010750,RADICAVA,EDARAVONE,RMP NDS NAS,06-Apr-18,22-May-18,27-Sep-18,Female,24,Manitoba,2018
42,MPMDB,Pharmaceuticals,209513,3010614,ORILISSA,ELAGOLIX,RMP NDS NAS,12-Dec-17,26-Feb-18,29-Jun-18,Female,24,Newfloudland Labrador,2018
43,MPMDB,Pharmaceuticals,217033,217033,IDHIFA,ENASIDENIB MESYLATE,RMP NDS NAS,13-Jul-18,27-Aug-18,18-Dec-18,Female,24,Newfloudland Labrador,2018
44,MPMDB,Pharmaceuticals,193890,3010492,MONOFER,FERRIC DERISOMALTOSE,RMP NDS NAS,07-Sep-17,22-Jan-18,18-May-18,Female,25,Newfloudland Labrador,2018
45,MPMDB,Pharmaceuticals,214274,3010740,TEGSEDI,INOTERSEN SODIUM,RMP NDS NAS,11-Apr-18,23-Apr-18,26-Sep-18,Female,25,Newfloudland Labrador,2018
46,MPMDB,Pharmaceuticals,207006,3010462,SOLIQUA,"INSULINE GLARGINE, LIXISENATIDE",RMP NDS NAS,25-Jul-17,15-Nov-17,05-Jun-18,Female,25,Newfloudland Labrador,2018
47,MPMDB,Pharmaceuticals,208919,3010728,CRESEMBA,ISAVUCONAZOLE,RMP NDS NAS,01-Apr-18,28-Jun-18,25-Oct-18,Female,25,Newfloudland Labrador,2018
48,MPMDB,Pharmaceuticals,211732,3010712,VYZULTA,LATANOPROSTENE BUNOD,RMP NDS NAS,19-Mar-18,21-Mar-18,25-Jul-18,Female,44,Newfloudland Labrador,2018
49,MPMDB,Pharmaceuticals,215733,215733,LORBRENA,LORLATINIB,RMP NDS NAS,12-Jun-18,04-Sep-18,19-Dec-18,Female,44,Quebec,2018
50,MPMDB,Pharmaceuticals,216257,216257,VLEXIO,NICARDIPINE HYDROCHLORIDE,RMP NDS NAS,26-Oct-18,30-Jan-19,22-Mar-19,Male,44,Quebec,2018
51,MPMDB,Pharmaceuticals,210368,210368,VELTASSA,PATIROMER SORBITEX CALCIUM,RMP NDS NAS,04-Dec-17,10-Jul-18,07-Nov-18,Male,44,Quebec,2018
52,MPMDB,Pharmaceuticals,207545,3010577,FOLOTYN,PRALATREXATE,RMP NDS NAS,28-Jan-18,06-Mar-18,07-Jun-18,Male,55,Ontario,2018
53,MPMDB,Pharmaceuticals,207115,3010772,ONSTRYV (XADAGO),SAFINAMIDE,RMP NDS NAS,16-Mar-18,15-May-18,21-Sep-18,Male,55,Ontario,2018
54,MPMDB,Pharmaceuticals,196367,3010777,BELSOMRA,SUVOREXANT,RMP NDS NAS,15-May-18,13-Aug-18,19-Dec-18,Female,55,Ontario,2018
55,MPMDB,Pharmaceuticals,211292,3010625,SYMDEKO,"TEZACAFTOR, IVACAFTOR",RMP NDS NAS,28-Nov-17,29-Jan-18,18-May-18,Female,55,Ontario,2018
56,MPMDB,Pharmaceuticals,206099,3010617,TIBELLA,TIBOLONE,RMP NDS NAS,24-Aug-17,03-Jan-18,04-May-18,Female,60,Ontario,2018
57,MPMDB,Pharmaceuticals,209280,3010518,WAYLIVRA,VOLANESORSEN,RMP NDS NAS,20-Sep-17,16-Nov-17,18-Apr-18,Female,61,Quebec,2018
58,MPMDB,Pharmaceuticals,209280,209280,WAYLIVRA,VOLANESORSEN,RMP NDS NAS,21-Aug-18,04-Sep-18,07-Nov-18,Female,34,Quebec,2018

In [11]:
# Rename colums in the dataset.
risk_management_new_drug_health_canada = risk_management_new_drug_health_canada.rename({'Lead_Office_Fro': 'Lead_Office', 'Product_Line': 'Categories_Product', 'SAP_No': 'File_No', 'Review_Type': 'Department_Review_Type'})
display(risk_management_new_drug_health_canada.head(59))

,Lead_Office_Fro,Product_Line,DSTS_No,SAP_No,Product_Name,Active_Ingred,Review_Type,Date_Received,Date_Assigned,Date_Finish,Gender,Age,Provinces,Fiscal_Year
0,MBBNHPB,Biologic,212387,3010678,BIOTHRAX,ANTHRAX VACCINE ADSORBED,RMP NDS,16-Feb-18,08-May-18,16-Sep-18,Male,23,Ontario,2018
1,MBBNHPB,Biologic,211541,3010633,KAMRAB,ANTI-RABIES IMMUNOGLOBIN (HUMAN),RMP NDS,12-Jan-18,27-Feb-18,04-Jun-18,Male,22,Ontario,2018
2,MBBNHPB,Biologic,210935,3010673,JIVI,"ANTIHEMOPHILIC FACTOR (RECOMBINANT), PEGYLATED",RMP NDS,08-Jan-18,13-Mar-18,05-Jul-18,Male,33,Ontario,2018
3,MBBNHPB,Biologic,208364,3010585,DWP-40,BOTULINUM TOXIN TYPE A,RMP NDS,20-Oct-17,30-Jan-18,29-May-18,Male,44,Ontario,2018
4,MBBNHPB,Biologic,212066,3010657,UNITUXIN,DINUTUXIMAB,RMP NDS,01-Feb-18,09-May-18,16-Sep-18,Male,55,Ontario,2018
5,MBBNHPB,Biologic,214080,3010766,NIVESTYM (BIOSIMILAR TO NEUPOGEN),FILGRASTIM,RMP NDS,16-Apr-18,13-Jun-18,16-Oct-18,Male,55,Ontario,2018
6,MBBNHPB,Biologic,212016,3010677,ZARXIO (BIOSIMILAR TO NEUPOGEN),FILGRASTIM,RMP NDS,05-Feb-18,08-May-18,17-Sep-18,Male,55,Ontario,2018
7,MBBNHPB,Biologic,214058,3010742,RIXATHON,RITUXIMAB,RMP NDS,20-Apr-18,19-Jul-18,19-Nov-18,Male,65,Ontario,2018
8,MBBNHPB,Biologic,566,3010655,TRAZIMERA,TRASTUZUMAB,RMP NDS,01-Feb-18,01-May-18,07-Sep-18,Female,65,Quebec,2018
9,MBBNHPB,Biologic,213188,3010711,VONVENDI,VON WILLEBRAND FACTOR [RECOMBINANT],RMP NDS,19-Mar-18,04-Jul-18,07-Nov-18,Female,65,Quebec,2018
10,MBBNHPB,Biologic,218389,3010866,YESCARTA,AXICABTAGENE CILOLEUCEL,RMP NDS NAS,17-Aug-18,10-Sep-18,11-Dec-18,Female,65,Quebec,2018
11,MBBNHPB,Biologic,216239,3010798,CRYSVITA,BUROSUMAB,RMP NDS NAS,08-Jun-18,14-Jun-18,01-Oct-18,Female,66,Quebec,2018
12,MBBNHPB,Biologic,218718,3010869,LIBTAYO,CEMIPLIMAB,RMP NDS NAS,24-Aug-18,30-Aug-18,17-Dec-18,Female,66,Quebec,2018
13,MBBNHPB,Biologic,218145,3010864,OXERVATE,CENEGERMIN,RMP NDS NAS,14-Aug-18,17-Aug-18,24-Dec-18,Female,66,Quebec,2018
14,MBBNHPB,Biologic,216539,3010817,BRINEURA,CERLIPONASE ALFA,RMP NDS NAS,25-Jun-18,04-Jul-18,12-Oct-18,Female,66,Manitoba,2018
15,MBBNHPB,Biologic,212635,3010672,HEMILIBRA,EMICIZUMAB,RMP NDS NAS,05-Feb-18,19-Feb-18,12-Jun-18,Female,45,Manitoba,2018
16,MBBNHPB,Biologic,208607,3010533,AIMOVIG,ERENUMAB,RMP NDS NAS,06-Oct-17,15-Jan-18,11-May-18,Female,23,Manitoba,2018
17,MBBNHPB,Biologic,212276,3010636,PANHEMATIN,HEMIN FOR INJECTION,RMP NDS NAS,16-Jan-18,24-Jan-18,24-Apr-18,Female,60,Manitoba,2018
18,MBBNHPB,Biologic,213920,3010731,TAKHZYRO,LANADELUMAB INJECTION,RMP NDS NAS,27-Mar-18,10-Apr-18,27-Jul-18,Male,60,Manitoba,2018
19,MBBNHPB,Biologic,217184,3010835,LUTATHERA,LUTETIUM (177LU OXODOTREOTIDE,RMP NDS NAS,13-Jul-18,19-Jul-18,06-Nov-18,Male,60,Nova-Scotia,2018
20,MBBNHPB,Biologic,215753,3010815,SKYRIZI,RISANKIZUMAB,RMP NDS NAS,22-Jun-18,02-Oct-18,12-Feb-19,Male,60,Prince Edward Island,2018
21,MBBNHPB,Biologic,197713,3010900,EVENITY,ROMOSOZUMAB,RMP NDS NAS,22-Aug-18,11-Oct-18,22-Jan-19,Male,60,Alberta,2018
22,MBBNHPB,Biologic,213,3010705,KYMRIAH,TISAGENLECLEUCEL,RMP NDS NAS,09-Mar-18,15-Mar-18,03-Jul-18,Female,67,Alberta,2018
23,MPMDB,Pharmaceuticals,209478,209478,AVIR-ACETAMINOPHEN INJECTION,ACETAMINOPHEN,RMP NDS,15-Apr-18,31-Jul-18,10-Oct-18,Female,67,Alberta,2018
24,MPMDB,Pharmaceuticals,215660,3010782,SUBLOCADE,BUPRENORPHINE,RMP NDS,25-May-18,07-Jun-18,18-Oct-18,Female,67,Saskatchewan,2018
25,MPMDB,Pharmaceuticals,211635,3010664,CYSTADROPS,CYSTEAMINE HYDROCHLORIDE,RMP NDS,19-Dec-17,14-Feb-18,19-Jun-18,Female,67,Saskatchewan,2018
26,MPMDB,Pharmaceuticals,201005,3010702,SEGLUROMET,"ERTUGLIFLOZIN, METFORMIN",RMP NDS,03-Aug-18,19-Apr-18,07-Aug-18,Female,67,Manitoba,2018
27,MPMDB,Pharmaceuticals,211970,3010761,NYXOID,NALOXONE HYDROCHLORIDE DIHYDRATE,RMP NDS,29-Jan-18,14-May-18,12-Sep-18,Male,59,Manitoba,2018
28,MPMDB,Pharmaceuticals,212391,3010685,NETILDEX,"NETILMICIN, DEXAMETHASONE SODIUM PHOSPHATE",RMP NDS,20-Feb-18,30-Apr-18,31-Aug-18,Male,49,Manitoba,2018
29,MPMDB,Pharmaceuticals,208730,3010611,XERMELO,TELOTRISTAT ETIPRATE,RMP NDS,13-Dec-17,30-Apr-18,24-Aug-18,Male,38,New-Brunswick,2018
30,MPMDB,Pharmaceuticals,215268,215268,VERZENIO,ABEMACICLIB,RMP NDS NAS,14-Jun-18,09-Oct-18,14-Feb-19,Male,25,New-Brunswick,2018
31,MPMDB,Pharmaceuticals,214504,214504,CALQUENCE,ACALABRUTINIB,RMP NDS NAS,24-Apr-18,17-Jul-18,07-Nov-18,Male,26,New-Brunswick,2018
32,MPMDB,Pharmaceuticals,217349,217349,TRANSLARNA,ATALUREN,RMP NDS NAS,13-Sep-18,04-Oct-18,21-Feb-19,Male,29,New-Brunswick,2018
33,MPMDB,Pharmaceuticals,193687,3010732,OLUMIANT,BARICITINIB,RMP NDS NAS,27-Mar-18,13-Apr-18,16-Aug-18,Female,32,New-Brunswick,2018
34,MPMDB,Pharmaceuticals,208886,3010627,BELEODAQ,BELINOSTAT,RMP NDS NAS,04-Mar-18,05-Jun-18,10-Oct-18,Female,32,New-Brunswick,2018
35,MPMDB,Pharmaceuticals,210369,3010624,ALUNBRIG,BRIGATINIB,RMP NDS NAS,21-Dec-17,10-Jan-18,11-May-18,Female,34,New-Brunswick,2018
36,MPMDB,Pharmaceuticals,212831,212831,CABOMETYX,CABOZANTINIB,RMP NDS NAS,18-Apr-18,04-Jul-18,01-Nov-18,Female,34,Manitoba,2018
37,MPMDB,Pharmaceuticals,214572,3010762,VIZIMPRO,DACOMITINIB,RMP NDS NAS,03-May-18,26-Sep-18,30-Jan-19,Female,34,Manitoba,2018
38,MPMDB,Pharmaceuticals,212390,3010735,XYDALBA,DALBAVANCIN,RMP NDS NAS,10-Apr-18,30-Apr-18,07-Sep-18,Female,19,Manitoba,2018
39,MPMDB,Pharmaceuticals,207372,3010736,DEMYLOCAN,DECITABINE,RMP NDS NAS,27-Mar-18,25-Jul-18,07-Dec-18,Female,19,Manitoba,2018
40,MPMDB,Pharmaceuticals,211293,3010610,TRADEMARK (DORAVIRINE),DORAVIRINE,RMP NDS NAS,10-Jan-18,27-Feb-18,20-Jun-18,Female,19,Manitoba,2018
41,MPMDB,Pharmaceuticals,214391,3010750,RADICAVA,EDARAVONE,RMP NDS NAS,06-Apr-18,22-May-18,27-Sep-18,Female,24,Manitoba,2018
42,MPMDB,Pharmaceuticals,209513,3010614,ORILISSA,ELAGOLIX,RMP NDS NAS,12-Dec-17,26-Feb-18,29-Jun-18,Female,24,Newfloudland Labrador,2018
43,MPMDB,Pharmaceuticals,217033,217033,IDHIFA,ENASIDENIB MESYLATE,RMP NDS NAS,13-Jul-18,27-Aug-18,18-Dec-18,Female,24,Newfloudland Labrador,2018
44,MPMDB,Pharmaceuticals,193890,3010492,MONOFER,FERRIC DERISOMALTOSE,RMP NDS NAS,07-Sep-17,22-Jan-18,18-May-18,Female,25,Newfloudland Labrador,2018
45,MPMDB,Pharmaceuticals,214274,3010740,TEGSEDI,INOTERSEN SODIUM,RMP NDS NAS,11-Apr-18,23-Apr-18,26-Sep-18,Female,25,Newfloudland Labrador,2018
46,MPMDB,Pharmaceuticals,207006,3010462,SOLIQUA,"INSULINE GLARGINE, LIXISENATIDE",RMP NDS NAS,25-Jul-17,15-Nov-17,05-Jun-18,Female,25,Newfloudland Labrador,2018
47,MPMDB,Pharmaceuticals,208919,3010728,CRESEMBA,ISAVUCONAZOLE,RMP NDS NAS,01-Apr-18,28-Jun-18,25-Oct-18,Female,25,Newfloudland Labrador,2018
48,MPMDB,Pharmaceuticals,211732,3010712,VYZULTA,LATANOPROSTENE BUNOD,RMP NDS NAS,19-Mar-18,21-Mar-18,25-Jul-18,Female,44,Newfloudland Labrador,2018
49,MPMDB,Pharmaceuticals,215733,215733,LORBRENA,LORLATINIB,RMP NDS NAS,12-Jun-18,04-Sep-18,19-Dec-18,Female,44,Quebec,2018
50,MPMDB,Pharmaceuticals,216257,216257,VLEXIO,NICARDIPINE HYDROCHLORIDE,RMP NDS NAS,26-Oct-18,30-Jan-19,22-Mar-19,Male,44,Quebec,2018
51,MPMDB,Pharmaceuticals,210368,210368,VELTASSA,PATIROMER SORBITEX CALCIUM,RMP NDS NAS,04-Dec-17,10-Jul-18,07-Nov-18,Male,44,Quebec,2018
52,MPMDB,Pharmaceuticals,207545,3010577,FOLOTYN,PRALATREXATE,RMP NDS NAS,28-Jan-18,06-Mar-18,07-Jun-18,Male,55,Ontario,2018
53,MPMDB,Pharmaceuticals,207115,3010772,ONSTRYV (XADAGO),SAFINAMIDE,RMP NDS NAS,16-Mar-18,15-May-18,21-Sep-18,Male,55,Ontario,2018
54,MPMDB,Pharmaceuticals,196367,3010777,BELSOMRA,SUVOREXANT,RMP NDS NAS,15-May-18,13-Aug-18,19-Dec-18,Female,55,Ontario,2018
55,MPMDB,Pharmaceuticals,211292,3010625,SYMDEKO,"TEZACAFTOR, IVACAFTOR",RMP NDS NAS,28-Nov-17,29-Jan-18,18-May-18,Female,55,Ontario,2018
56,MPMDB,Pharmaceuticals,206099,3010617,TIBELLA,TIBOLONE,RMP NDS NAS,24-Aug-17,03-Jan-18,04-May-18,Female,60,Ontario,2018
57,MPMDB,Pharmaceuticals,209280,3010518,WAYLIVRA,VOLANESORSEN,RMP NDS NAS,20-Sep-17,16-Nov-17,18-Apr-18,Female,61,Quebec,2018
58,MPMDB,Pharmaceuticals,209280,209280,WAYLIVRA,VOLANESORSEN,RMP NDS NAS,21-Aug-18,04-Sep-18,07-Nov-18,Female,34,Quebec,2018

In [12]:
risk_management_new_drug_health_canada = risk_management_new_drug_health_canada.rename(columns={'Lead_Office_Fro': 'Lead_Office', 'Product_Line': 'Categories_Product', 'SAP_No': 'File_No', 'Review_Type': 'Department_Review_Type'})
display(risk_management_new_drug_health_canada.head(59))

,Lead_Office,Categories_Product,DSTS_No,File_No,Product_Name,Active_Ingred,Department_Review_Type,Date_Received,Date_Assigned,Date_Finish,Gender,Age,Provinces,Fiscal_Year
0,MBBNHPB,Biologic,212387,3010678,BIOTHRAX,ANTHRAX VACCINE ADSORBED,RMP NDS,16-Feb-18,08-May-18,16-Sep-18,Male,23,Ontario,2018
1,MBBNHPB,Biologic,211541,3010633,KAMRAB,ANTI-RABIES IMMUNOGLOBIN (HUMAN),RMP NDS,12-Jan-18,27-Feb-18,04-Jun-18,Male,22,Ontario,2018
2,MBBNHPB,Biologic,210935,3010673,JIVI,"ANTIHEMOPHILIC FACTOR (RECOMBINANT), PEGYLATED",RMP NDS,08-Jan-18,13-Mar-18,05-Jul-18,Male,33,Ontario,2018
3,MBBNHPB,Biologic,208364,3010585,DWP-40,BOTULINUM TOXIN TYPE A,RMP NDS,20-Oct-17,30-Jan-18,29-May-18,Male,44,Ontario,2018
4,MBBNHPB,Biologic,212066,3010657,UNITUXIN,DINUTUXIMAB,RMP NDS,01-Feb-18,09-May-18,16-Sep-18,Male,55,Ontario,2018
5,MBBNHPB,Biologic,214080,3010766,NIVESTYM (BIOSIMILAR TO NEUPOGEN),FILGRASTIM,RMP NDS,16-Apr-18,13-Jun-18,16-Oct-18,Male,55,Ontario,2018
6,MBBNHPB,Biologic,212016,3010677,ZARXIO (BIOSIMILAR TO NEUPOGEN),FILGRASTIM,RMP NDS,05-Feb-18,08-May-18,17-Sep-18,Male,55,Ontario,2018
7,MBBNHPB,Biologic,214058,3010742,RIXATHON,RITUXIMAB,RMP NDS,20-Apr-18,19-Jul-18,19-Nov-18,Male,65,Ontario,2018
8,MBBNHPB,Biologic,566,3010655,TRAZIMERA,TRASTUZUMAB,RMP NDS,01-Feb-18,01-May-18,07-Sep-18,Female,65,Quebec,2018
9,MBBNHPB,Biologic,213188,3010711,VONVENDI,VON WILLEBRAND FACTOR [RECOMBINANT],RMP NDS,19-Mar-18,04-Jul-18,07-Nov-18,Female,65,Quebec,2018
10,MBBNHPB,Biologic,218389,3010866,YESCARTA,AXICABTAGENE CILOLEUCEL,RMP NDS NAS,17-Aug-18,10-Sep-18,11-Dec-18,Female,65,Quebec,2018
11,MBBNHPB,Biologic,216239,3010798,CRYSVITA,BUROSUMAB,RMP NDS NAS,08-Jun-18,14-Jun-18,01-Oct-18,Female,66,Quebec,2018
12,MBBNHPB,Biologic,218718,3010869,LIBTAYO,CEMIPLIMAB,RMP NDS NAS,24-Aug-18,30-Aug-18,17-Dec-18,Female,66,Quebec,2018
13,MBBNHPB,Biologic,218145,3010864,OXERVATE,CENEGERMIN,RMP NDS NAS,14-Aug-18,17-Aug-18,24-Dec-18,Female,66,Quebec,2018
14,MBBNHPB,Biologic,216539,3010817,BRINEURA,CERLIPONASE ALFA,RMP NDS NAS,25-Jun-18,04-Jul-18,12-Oct-18,Female,66,Manitoba,2018
15,MBBNHPB,Biologic,212635,3010672,HEMILIBRA,EMICIZUMAB,RMP NDS NAS,05-Feb-18,19-Feb-18,12-Jun-18,Female,45,Manitoba,2018
16,MBBNHPB,Biologic,208607,3010533,AIMOVIG,ERENUMAB,RMP NDS NAS,06-Oct-17,15-Jan-18,11-May-18,Female,23,Manitoba,2018
17,MBBNHPB,Biologic,212276,3010636,PANHEMATIN,HEMIN FOR INJECTION,RMP NDS NAS,16-Jan-18,24-Jan-18,24-Apr-18,Female,60,Manitoba,2018
18,MBBNHPB,Biologic,213920,3010731,TAKHZYRO,LANADELUMAB INJECTION,RMP NDS NAS,27-Mar-18,10-Apr-18,27-Jul-18,Male,60,Manitoba,2018
19,MBBNHPB,Biologic,217184,3010835,LUTATHERA,LUTETIUM (177LU OXODOTREOTIDE,RMP NDS NAS,13-Jul-18,19-Jul-18,06-Nov-18,Male,60,Nova-Scotia,2018
20,MBBNHPB,Biologic,215753,3010815,SKYRIZI,RISANKIZUMAB,RMP NDS NAS,22-Jun-18,02-Oct-18,12-Feb-19,Male,60,Prince Edward Island,2018
21,MBBNHPB,Biologic,197713,3010900,EVENITY,ROMOSOZUMAB,RMP NDS NAS,22-Aug-18,11-Oct-18,22-Jan-19,Male,60,Alberta,2018
22,MBBNHPB,Biologic,213,3010705,KYMRIAH,TISAGENLECLEUCEL,RMP NDS NAS,09-Mar-18,15-Mar-18,03-Jul-18,Female,67,Alberta,2018
23,MPMDB,Pharmaceuticals,209478,209478,AVIR-ACETAMINOPHEN INJECTION,ACETAMINOPHEN,RMP NDS,15-Apr-18,31-Jul-18,10-Oct-18,Female,67,Alberta,2018
24,MPMDB,Pharmaceuticals,215660,3010782,SUBLOCADE,BUPRENORPHINE,RMP NDS,25-May-18,07-Jun-18,18-Oct-18,Female,67,Saskatchewan,2018
25,MPMDB,Pharmaceuticals,211635,3010664,CYSTADROPS,CYSTEAMINE HYDROCHLORIDE,RMP NDS,19-Dec-17,14-Feb-18,19-Jun-18,Female,67,Saskatchewan,2018
26,MPMDB,Pharmaceuticals,201005,3010702,SEGLUROMET,"ERTUGLIFLOZIN, METFORMIN",RMP NDS,03-Aug-18,19-Apr-18,07-Aug-18,Female,67,Manitoba,2018
27,MPMDB,Pharmaceuticals,211970,3010761,NYXOID,NALOXONE HYDROCHLORIDE DIHYDRATE,RMP NDS,29-Jan-18,14-May-18,12-Sep-18,Male,59,Manitoba,2018
28,MPMDB,Pharmaceuticals,212391,3010685,NETILDEX,"NETILMICIN, DEXAMETHASONE SODIUM PHOSPHATE",RMP NDS,20-Feb-18,30-Apr-18,31-Aug-18,Male,49,Manitoba,2018
29,MPMDB,Pharmaceuticals,208730,3010611,XERMELO,TELOTRISTAT ETIPRATE,RMP NDS,13-Dec-17,30-Apr-18,24-Aug-18,Male,38,New-Brunswick,2018
30,MPMDB,Pharmaceuticals,215268,215268,VERZENIO,ABEMACICLIB,RMP NDS NAS,14-Jun-18,09-Oct-18,14-Feb-19,Male,25,New-Brunswick,2018
31,MPMDB,Pharmaceuticals,214504,214504,CALQUENCE,ACALABRUTINIB,RMP NDS NAS,24-Apr-18,17-Jul-18,07-Nov-18,Male,26,New-Brunswick,2018
32,MPMDB,Pharmaceuticals,217349,217349,TRANSLARNA,ATALUREN,RMP NDS NAS,13-Sep-18,04-Oct-18,21-Feb-19,Male,29,New-Brunswick,2018
33,MPMDB,Pharmaceuticals,193687,3010732,OLUMIANT,BARICITINIB,RMP NDS NAS,27-Mar-18,13-Apr-18,16-Aug-18,Female,32,New-Brunswick,2018
34,MPMDB,Pharmaceuticals,208886,3010627,BELEODAQ,BELINOSTAT,RMP NDS NAS,04-Mar-18,05-Jun-18,10-Oct-18,Female,32,New-Brunswick,2018
35,MPMDB,Pharmaceuticals,210369,3010624,ALUNBRIG,BRIGATINIB,RMP NDS NAS,21-Dec-17,10-Jan-18,11-May-18,Female,34,New-Brunswick,2018
36,MPMDB,Pharmaceuticals,212831,212831,CABOMETYX,CABOZANTINIB,RMP NDS NAS,18-Apr-18,04-Jul-18,01-Nov-18,Female,34,Manitoba,2018
37,MPMDB,Pharmaceuticals,214572,3010762,VIZIMPRO,DACOMITINIB,RMP NDS NAS,03-May-18,26-Sep-18,30-Jan-19,Female,34,Manitoba,2018
38,MPMDB,Pharmaceuticals,212390,3010735,XYDALBA,DALBAVANCIN,RMP NDS NAS,10-Apr-18,30-Apr-18,07-Sep-18,Female,19,Manitoba,2018
39,MPMDB,Pharmaceuticals,207372,3010736,DEMYLOCAN,DECITABINE,RMP NDS NAS,27-Mar-18,25-Jul-18,07-Dec-18,Female,19,Manitoba,2018
40,MPMDB,Pharmaceuticals,211293,3010610,TRADEMARK (DORAVIRINE),DORAVIRINE,RMP NDS NAS,10-Jan-18,27-Feb-18,20-Jun-18,Female,19,Manitoba,2018
41,MPMDB,Pharmaceuticals,214391,3010750,RADICAVA,EDARAVONE,RMP NDS NAS,06-Apr-18,22-May-18,27-Sep-18,Female,24,Manitoba,2018
42,MPMDB,Pharmaceuticals,209513,3010614,ORILISSA,ELAGOLIX,RMP NDS NAS,12-Dec-17,26-Feb-18,29-Jun-18,Female,24,Newfloudland Labrador,2018
43,MPMDB,Pharmaceuticals,217033,217033,IDHIFA,ENASIDENIB MESYLATE,RMP NDS NAS,13-Jul-18,27-Aug-18,18-Dec-18,Female,24,Newfloudland Labrador,2018
44,MPMDB,Pharmaceuticals,193890,3010492,MONOFER,FERRIC DERISOMALTOSE,RMP NDS NAS,07-Sep-17,22-Jan-18,18-May-18,Female,25,Newfloudland Labrador,2018
45,MPMDB,Pharmaceuticals,214274,3010740,TEGSEDI,INOTERSEN SODIUM,RMP NDS NAS,11-Apr-18,23-Apr-18,26-Sep-18,Female,25,Newfloudland Labrador,2018
46,MPMDB,Pharmaceuticals,207006,3010462,SOLIQUA,"INSULINE GLARGINE, LIXISENATIDE",RMP NDS NAS,25-Jul-17,15-Nov-17,05-Jun-18,Female,25,Newfloudland Labrador,2018
47,MPMDB,Pharmaceuticals,208919,3010728,CRESEMBA,ISAVUCONAZOLE,RMP NDS NAS,01-Apr-18,28-Jun-18,25-Oct-18,Female,25,Newfloudland Labrador,2018
48,MPMDB,Pharmaceuticals,211732,3010712,VYZULTA,LATANOPROSTENE BUNOD,RMP NDS NAS,19-Mar-18,21-Mar-18,25-Jul-18,Female,44,Newfloudland Labrador,2018
49,MPMDB,Pharmaceuticals,215733,215733,LORBRENA,LORLATINIB,RMP NDS NAS,12-Jun-18,04-Sep-18,19-Dec-18,Female,44,Quebec,2018
50,MPMDB,Pharmaceuticals,216257,216257,VLEXIO,NICARDIPINE HYDROCHLORIDE,RMP NDS NAS,26-Oct-18,30-Jan-19,22-Mar-19,Male,44,Quebec,2018
51,MPMDB,Pharmaceuticals,210368,210368,VELTASSA,PATIROMER SORBITEX CALCIUM,RMP NDS NAS,04-Dec-17,10-Jul-18,07-Nov-18,Male,44,Quebec,2018
52,MPMDB,Pharmaceuticals,207545,3010577,FOLOTYN,PRALATREXATE,RMP NDS NAS,28-Jan-18,06-Mar-18,07-Jun-18,Male,55,Ontario,2018
53,MPMDB,Pharmaceuticals,207115,3010772,ONSTRYV (XADAGO),SAFINAMIDE,RMP NDS NAS,16-Mar-18,15-May-18,21-Sep-18,Male,55,Ontario,2018
54,MPMDB,Pharmaceuticals,196367,3010777,BELSOMRA,SUVOREXANT,RMP NDS NAS,15-May-18,13-Aug-18,19-Dec-18,Female,55,Ontario,2018
55,MPMDB,Pharmaceuticals,211292,3010625,SYMDEKO,"TEZACAFTOR, IVACAFTOR",RMP NDS NAS,28-Nov-17,29-Jan-18,18-May-18,Female,55,Ontario,2018
56,MPMDB,Pharmaceuticals,206099,3010617,TIBELLA,TIBOLONE,RMP NDS NAS,24-Aug-17,03-Jan-18,04-May-18,Female,60,Ontario,2018
57,MPMDB,Pharmaceuticals,209280,3010518,WAYLIVRA,VOLANESORSEN,RMP NDS NAS,20-Sep-17,16-Nov-17,18-Apr-18,Female,61,Quebec,2018
58,MPMDB,Pharmaceuticals,209280,209280,WAYLIVRA,VOLANESORSEN,RMP NDS NAS,21-Aug-18,04-Sep-18,07-Nov-18,Female,34,Quebec,2018